### ISSUE TITLE
附加信息

### ISSUE THREAD

**Issue by wxyttty** [Inuyashaaaaa/fzuDailyCampus#2]
怎么提交附加信息
无论是把附加信息放在"extraFieldItemVos" "extraField" "signedStuInfo" "extraFieldItems"哪个里提交后附加信息都没填。应该怎么提交附加选项?

POST /wec-counselor-sign-apps/stu/sign/detailSignInstance HTTP/1.1

{"code":"0","message":"SUCCESS","datas":{"signInstanceWid":"45069","signMode":0,"signRate":"1","signCondition":0,"taskType":"1","taskName":"健康监测—午报告","taskDesc":"https://wecres.cpdaily.com/counselor/1018615892395240/content/9ba6ede3a8b74f9c84666040013163d9.html","qrCodeRcvdUsers":[{"targetWid":"91416543","targetType":"4","targetName":"蔺际俨/T13049","targetGrade":"-1","targetDegree":"-1","targetUserType":"-1"}],"senderUserName":"数学与计算机科学学院(程瑶函)","currentTime":"2020-09-01 11:17:46","singleTaskBeginTime":null,"singleTaskEndTime":null,"rateSignDate":"2020-09-01 (周二)","rateTaskBeginTime":"11:00","rateTaskEndTime":"14:00","signStatus":"1","signTime":"2020-09-01 11:03:29","signPhotoUrl":"","signType":1,"changeTime":"2020-09-01 11:03:29","changeActorName":"吴新宇","signPlaceSelected":[{"wid":null,"placeWid":null,"address":"福

**Comment by wxyttty** [comment]
州大学第二田径场","longitude":"119.203149","latitude":"26.062701","radius":1100,"creatorUserWid":null,"creatorUserId":null,"creatorName":null,"currentStatus":null,"isShare":null},{"wid":null,"placeWid":null,"address":"福州大学(铜盘校区)","longitude":"119.268733","latitude":"26.111404","radius":400,"creatorUserWid":null,"creatorUserId":null,"creatorName":null,"currentStatus":null,"isShare":null},{"wid":null,"placeWid":null,"address":"福州大学石油化工学院泉港校区-南门","longitude":"118.855656","latitude":"25.139465","radius":440,"creatorUserWid":null,"creatorUserId":null,"creatorName":null,"currentStatus":null,"isShare":null},{"wid":null,"placeWid":null,"address":"福州大学厦门工艺美术学院(集美校区)","longitude":"118.096462","latitude":"24.640359","radius":340,"creatorUserWid":null,"creatorUserId":null,"creatorName":null,"currentStatus":null,"isShare":null},{"wid":null,"placeWid":null,"address":"金井镇","longitude":"118.591619","latitude":"24.56466","radius":630,"creatorUserWid":null,"creatorUserId":null,"creatorName":null,"currentStatus":null,"isShare":null}],"isPhoto":0,"photograph":[],"downloadUrl":"https://img.cpdaily.com/ldy/index.html","leaveAppUrl":"/wec-counselor-leave-apps/leave/home/index.html","catQrUrl":"https://cat.cpdaily.com/erweima","signAddress":"中国福建省福州市闽侯县学府南路","longitude":"119.199047","latitude":"26.056564","isMalposition":0,"signedStuInfo":{"userWid":"1016929993","userId":"031701228","userName":"","sex":"","nation":"-","mobile":null,"grade":"2017级","dept":"","major":"","cls":"","schoolStatus":null,"malposition":null,"stuDormitoryVo":{"area":"","building":"","unit":"","room":"","sex":""},"extraFieldItemVos":[{"fieldIndex":0,"extraTitle":"午检体温 (必填)","extraDesc":"请如实填报","extraFieldItemWid":"73583","extraFieldItem":"小于37.3度","isExtraFieldOtherItem":"0","isAbnormal":"0"},{"fieldIndex":0,"extraTitle":"是否有发热、咳嗽、乏力、呼吸困难等疑似症状(必填)","extraDesc":"请如实填报","extraFieldItemWid":"73585","extraFieldItem":"否","isExtraFieldOtherItem":"0","isAbnormal":"0"}]},"isNeedExtra":1,"isAllowUpdate":true,"extraField":[{"wid":32161,"title":"午检体温 (必填)","description":"请如实填报","hasOtherItems":0,"extraFieldItems":[{"content":"小于37.3度","wid":73583,"isOtherItems":0,"value":"小于37.3度","isSelected":true,"isAbnormal":false},{"content":"大于等于37.3度","wid":73584,"isOtherItems":0,"value":null,"isSelected":null,"isAbnormal":true}]},{"wid":32162,"title":"是否有发热、咳嗽、乏力、呼吸困难等疑似症状(必填)","description":"请如实填报","hasOtherItems":0,"extraFieldItems":[{"content":"否","wid":73585,"isOtherItems":0,"value":"否","isSelected":true,"isAbnormal":false},{"content":"是","wid":73586,"isOtherItems":0,"value":null,"isSelected":null,"isAbnormal":true}]}],"extraFieldItemVos":[]}}

**Comment by Inuyashaaaaa** [comment]
你可以参考让一个issue，现在我搬宿舍没有电信网络，暂时没有抓包，所以最新的还没有上线，现在无法支持每日三报功能。

**Comment by wxyttty** [comment]
。。上一个就是我的，只是搞了定位。抓包的话怎么抓到提交的时候的包？我抓包他就不能提交

**Comment by Inuyashaaaaa** [comment]
应该是证书的问题，你没有被信任

**Comment by Inuyashaaaaa** [comment]
附加信息我还在看，终于有网了，明天应该可以搞定

**Comment by wxyttty** [comment]
证书怎么信任呢，我搞了系统证书，justtrustme，ssl unpinning都不行

**Comment by Inuyashaaaaa** [comment]
你可以尝试在 submitSign接口中这样填写内容

```
"extraFieldItems": [
    { "extraFieldItemValue": "小于37.3度", "extraFieldItemWid": 73925 },
    { "extraFieldItemValue": "否", "extraFieldItemWid": 73927 }
  ]
```

其中extraFieldItemWid 是请求 detailSignInstance接口得到的

**Comment by wxyttty** [comment]
发现之前的extraFieldItemWid写成extraFieldItemwid了，晚上试试

**Comment by wxyttty** [comment]
成功

**Comment by wxyttty** [comment]
wxy1958517281@163.com
